name: "Align CI"

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - '*'

jobs:
  macos-run-tests:
    name: Unit Tests (macOS, Xcode 15.3)
    runs-on: macOS-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: swift test

  ios-run-tests-15:
    name: Unit Tests (iOS 17.3, Xcode 15.3)
    runs-on: macOS-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: xcodebuild test -scheme "Align" -destination "OS=17.3,name=iPhone 15 Pro"

  ios-run-tests-14:
    name: Unit Tests (iOS 16.4, Xcode 14.3.1)
    runs-on: macOS-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: xcodebuild test -scheme "Align" -destination "OS=16.4,name=iPhone 14 Pro"
